### ISSUE TITLE
Can't create new IAM user

### ISSUE THREAD

**Issue by c9katayama** [amazon-archives/aws-sdk-java-resources#14]
Hi,
I tried to create new IAM user with following code.

``` java
IdentityManagement iam = ServiceBuilder.forService(IdentityManagement.class).withCredentials(new ClasspathPropertiesFileCredentialsProvider()).build();
User iamUse = iam.createUser(new CreateUserRequest("SDKSAMPLE"));
```

but I got an error when calling createUser mathod. Here is a stack trace.

``` java
Exception in thread "main" java.lang.IllegalArgumentException: Illegal Capacity: -1
    at java.util.ArrayList.<init>(ArrayList.java:146)
    at com.amazonaws.resources.internal.ActionUtils.extractMultiValuedIdentifiers(ActionUtils.java:372)
    at com.amazonaws.resources.internal.ActionUtils.extractIdentifiers(ActionUtils.java:266)
    at com.amazonaws.resources.internal.ActionUtils.getResultResources(ActionUtils.java:223)
    at com.amazonaws.resources.internal.ActionUtils.perform(ActionUtils.java:115)
    at com.amazonaws.resources.internal.ActionUtils.perform(ActionUtils.java:60)
    at com.amazonaws.resources.internal.ServiceImpl.performAction(ServiceImpl.java:116)
    at com.amazonaws.resources.identitymanagement.internal.IdentityManagementImpl.createUser(IdentityManagementImpl.java:344)
    at com.amazonaws.resources.identitymanagement.internal.IdentityManagementImpl.createUser(IdentityManagementImpl.java:337)
    at aws_resource_api_samples.App.main(App.java:34)
```

I investigated source code. The error occurs when read attiributes a CreateUserResult that is a return value of API call for AWS.
It seems that list size check is needed in ActionUtils#extractMultiValuedIdentifiers.

**Comment by david-at-aws** [comment]
Hey Akio, thanks for reporting this! I'll get a fix together right away.

**Comment by david-at-aws** [comment]
Fix has been merged into master. You can pick it up now by building from source; it'll be available in maven when we cut the next release. Thanks again for reporting this!
